### ISSUE TITLE
Consider making unset a Symbol and preventing update of orphan values.

### ISSUE THREAD

**Issue by motherthestate** [Rinaldo/evolve-ts#1]
Hey, suggesting making unset a symbol allowing it to be used conditionally without new keyword,
```javascript
const c = evolve({ a: v => v || unset })

c({ a: undefined }) // {}
c({ a: 5 }) // { a: 5 }
``` 
I also tried finding a way of preventing the creation of entries if their parent isn't present in the target object. The addition of a second orphan parameter to help differentiate between deep unset values and `undefined` would work . But would cause type problems with tacit function invocations.
```javascript
const c = evolve({ a: { b: { c: { d: { e: (, orphan) => orphan ? unset : 5 } } } } })

c({}) // {}
c({ a: { b: { c: { d: {} } } } }) // { a: { b: { c: { d: { e: 5 } } } } }
```
I think this would be useful even if it is integrated differently. Would you be interested in finding a good way of achieving this? I'd love to contribute on this project.

**Comment by Rinaldo** [comment]
Hi, thanks for the suggestions! I agree it would be nice to be able to remove values conditionally. Allowing updater functions to return `unset` makes sense.

As for preventing the creation of entries that don't already exist, right now this package leans on TypeScript to do that. Are you using TypeScript? If so it should prevent you from defining keys in the patch that don't exist in the target.

I'm a little unsure how you're defining `orphan` in your second example but I'd rather not change the function signature of the updater functions.

**Comment by Rinaldo** [comment]
I just published a new version so updater functions can return `unset`. This allows for removing keys conditionally.

I'm still unsure about adding a runtime check to prevent the creation of new keys as opposed to relying on TypeScript, but feel free to open another issue if the type checks aren't working or you feel that a runtime check is important.
